### ISSUE TITLE
Create instance of object type with complex data types as parameters

### ISSUE THREAD

**Issue by Lessi30** [Traeger-GmbH/opcuanet-samples#15]
Dear Traeger Team

I am having difficulties instantiating an ObjectType. Briefly a little context. I have my own nodeset. This nodeset is imported correctly in my own NodeManager. The server's address space recognises all the types contained in my nodeset. Now I want to instantiate my ObjectType. As far as I understand now I have to rebuild my complete object with the inheritance of OpcObjectNode. 

So if I get the node here and then add it to the AddressSpace, then it is not an instance, but only the type, but the types of the method parameters match. 

```csharp
public class ArtemisNodeManager() : OpcNodeManager("http://opcfoundation.org/UA/Machinery/", "http://opcfoundation.org/UA/DI/", "http://localhost.com/Artemis/")
{
    protected override IEnumerable<OpcNodeSet> ImportNodes()
    {
        yield return OpcNodeSet.Load(@".\NodeSets\Opc.Ua.Di.NodeSet2.xml");
        yield return OpcNodeSet.Load(@".\NodeSets\Opc.Ua.Machinery.NodeSet2.xml");
        yield return OpcNodeSet.Load(@".\NodeSets\Artemis.NodeSet2.xml");
    }

    protected override IEnumerable<IOpcNode> CreateNodes(OpcNodeReferenceCollection references)
    {
        base.CreateNodes(references);

        var jobListNode = FindNodeByNamespaceAndId(4, 1022);

        references.Add(jobListNode.Id, OpcObjectTypes.ObjectsFolder);

        return new[] { jobListNode };
    }

    private IOpcNode FindNodeByNamespaceAndId(ushort namespaceIndex, uint nodeId)
    {
        var opcNodeId = new OpcNodeId(nodeId, namespaceIndex);

        var node = Nodes.FirstOrDefault(node => node.Id == opcNodeId);

        if (node is null)
        {
            throw new Exception($"Could not find a node with provided id: ns={namespaceIndex};i={nodeId}");
        }

        return node;
    }
}
```

If I create my own type, then I either have to add all references manually again, because otherwise it doesn't know its methods, or if I add the method manually, it doesn't know my data type either. So it simply expects Structure instead of my own type.

```csharp
public sealed class JobListObjectNode : OpcObjectNode
    {
        private readonly Dictionary<string, JobData> _jobList = new Dictionary<string, JobData>();

        private OpcMethodNode _addJobMethod;
        private OpcMethodNode _deleteJobMethod;
        private OpcMethodNode _listJobsMethod;
        private OpcMethodNode _getJobByIdentifierMethod;

        public JobListObjectNode(OpcName name)
            : base(name)
        {
            this.InitializeChildren();
        }
        protected override OpcNodeId DefaultTypeDefinitionId
        {
            get => "ns=4;i=1022";
        }

        public JobListObjectNode(IOpcNode parent, OpcName name)
            : base(parent, name)
        {
            this.InitializeChildren();
        }

        public uint AddJob(NewJobData jobData)
        {
            if (string.IsNullOrWhiteSpace(jobData.JobIdentifier) &&
                string.IsNullOrWhiteSpace(jobData.JobName))
            {
                return 101u;
            }

            if (_jobList.ContainsKey(jobData.JobIdentifier))
            {
                return 404u;
            }

            _jobList[jobData.JobIdentifier] = new JobData(jobData);

            return 0;
        }

        public uint DeleteJob(string jobIdentifier)
        {
            if (string.IsNullOrWhiteSpace(jobIdentifier))
            {
                return 101u;
            }

            return _jobList.Remove(jobIdentifier)
                ? 0
                : 404u;
        }

        public (uint Status, JobEntryData[] JobList) ListJobs()
        {
            return (0, _jobList.Values.Select(j => new JobEntryData(j.JobIdentifier, j.JobName)).ToArray());
        }

        public (uint Status, JobData JobData) GetJobByIdentifier(string jobIdentifier)
        {
            if (!_jobList.TryGetValue(jobIdentifier, out JobData? jobData))
            {
                return (404u, default);
            }
            else
            {
                return (0, jobData);
            }
        }

        private void InitializeChildren()
        {
            this._addJobMethod = new OpcMethodNode(
                parent: this,
                name: "4:AddJob",
                callback: new Func<NewJobData, uint>(AddJob));

            this._deleteJobMethod = new OpcMethodNode(
                parent: this,
                name: "4:DeleteJob",
                callback: new Func<string, uint>(DeleteJob));
        }
    }
```

If I create my own type, then I either have to add all references manually again, because otherwise it doesn't know its methods, or if I add the method manually, it doesn't know my data type either. So it simply expects Structure instead of my own type. 

So in the end I need: An instance of my JobListType with the existing 4 methods. When calling methods, the server knows the types that the method must accept. And the methods must be bound to my type so that the methods in my class are executed with the correct types when the method is called.

```csharp
public sealed class JobListType
{
    private readonly Dictionary<string, JobDataType> _jobList = [];

    internal JobListType()
    {
    }

    public uint AddJob(NewJobDataType jobData)
    {
        if (string.IsNullOrWhiteSpace(jobData.JobIdentifier) &&
            string.IsNullOrWhiteSpace(jobData.JobName))
        {
            return 101u;
        }

        if (_jobList.ContainsKey(jobData.JobIdentifier))
        {
            return 404u;
        }

        _jobList[jobData.JobIdentifier] = new JobDataType(jobData);

        return 0;
    }

    public uint DeleteJob(string jobIdentifier)
    {
        if (string.IsNullOrWhiteSpace(jobIdentifier))
        {
            return 101u;
        }

        return _jobList.Remove(jobIdentifier)
            ? 0
            : 404u;
    }

    public (uint Status, JobEntryDataType[] JobList) ListJobs()
    {
        return (0, [.. _jobList.Values.Select(j => new JobEntryDataType(j.JobIdentifier, j.JobName))]);
    }

    public (uint Status, JobDataType JobData) GetJobByIdentifier(string jobIdentifier)
    {
        if (!_jobList.TryGetValue(jobIdentifier, out JobDataType? jobData))
        {
            return (404u, JobDataType.Emtpy);
        }
        else
        {
            return (0, jobData);
        }
    }
}
```

If you need further information or have any questions, feel free to ask and i try to answer in short time. 

Thanks for helping!

**Comment by 19blue85** [comment]
Dear Sir or Madame,
have you already tried to use the ImplementNode method? At https://github.com/Traeger-GmbH/opcuanet-samples/issues/14 you will find more information. When all the needed data is in the NodeSet you should be able to use the implemented Nodes.
Otherwise you need to implement all data types, which are not in the NodeSet in the NodeManager.

Please feel free to ask, when you need further help or information.

**Comment by Lessi30** [comment]
I have already looked at the issue mentioned. But it is not an exact answer to my question. 

So to be on the safe side: There is a ModelCompiler in the Foundation SDK. This throws out generated code that represents the objects. So in my case, it creates a JobListTypeState for the JobListType, which inherits from BaseObjectState and the corresponding classes are also generated for all childelements. I then map this generated output to my own types, which is not a problem as my types remain unchanged and the rest is generated. But in this case I would have to rebuild the 1000 lines long structure. Of course, not like the Foundation SDK, which inherits from BaseObjectState, but in this case with the Traeger types, e.g. inheritance from OpcObjectNode. 

But I would still have to map these to my own types so that my project only knows the properties of my type externally and not the whole OPC story in the background, right?

Im going to create a small simple repository for this issue for you to unterstand me a bit better.

**Comment by 19blue85** [comment]
Dear Sir or Madame,
your programming is so far correct. You need to implement all Nodes, which are not provided by the NodeSet by yourself. So if even the Datatype is described in the NodeSet, you need to implement all needed data by yourself. 
You can do following: Start the OPC UA Server with the NodeSet(s) and then use our OPC Watch to generate the needed datatypes, like described at https://docs.traeger.de/en/software/sdk/opc-ua/net/client.development.guide#generate-data-types. This generated classes can be used then in your OPC UA Server application. 
You will find the datatypes under the Types-Folder:

![Image](https://github.com/user-attachments/assets/445abea6-424c-4cf1-9709-e047d72de53c)

When the NodeSet provides still a Node for a type or method, then you need to use the ImplementNode method.

Please feel free to ask, when you need further information or help.

**Comment by Lessi30** [comment]
We are currently observing the following bahvior:

- DataTypes created by loading a node set are showing an incomplete structure definition if inheritance is involved. In our demo node set see JobEntryDataType and NewJobDataType.
- - When trying to call the AddJob method from an OPC client, for example UaExpert, the structure is not shown completely 
- Creating the data types manually leads to the expected definitions and behavior when calling the AddJob method.

Please have a look at the [demo repo](https://github.com/Lessi30/traeger-sdk-issue-15) and get back to me. I would really appreciate any feedback on how to address this issue.

@19blue85 @kpreisser @dscharnagl ?

**Comment by kpreisser** [comment]
Hi @Lessi30,
thanks for your reply and providing the demo project! I'm sorry for the delay.

In this case, unfortunately there is a known issue in our SDK when importing a node set containing inherited structured data types, in which case the inherited type does not contain the fields from the base type in the `DataTypeDefinition` attribute.
We are currently working on fixing the issue, but please note this may take some time, due to some colleagues currently being unavailable.
Thanks!

**Comment by kpreisser** [comment]
Hi @Lessi30,

we have released a new preview version of `Opc.UaFx.Advanced` and `Opc.UaFx.Client`, `2.43.0.0-preview.1`, which includes a possible fix for this issue. The new version is available on NuGet: https://www.nuget.org/packages/Opc.UaFx.Advanced/2.43.0-preview.1

To enable the fix, you will need to set the `OpcNodeSetImportOptions.CompleteDataTypeDefinitionFields` flag, e.g. when using the `OpcNodeSetManager`:
```cs
var nodeSetManager = OpcNodeSetManager.Create(OpcNodeSet.Load(@"nodeSet.xml"));
nodeSetManager.ImportOptions = OpcNodeSetImportOptions.CompleteDataTypeDefinitionFields;
```

Or, when using a subclass of `OpcNodeManager`, the options can be set via `this.NodeSetImportOptions = ...`.

When this option is set, the `DataTypeDefinition` attribute of structured data types derived from another structured data type should correctly show the fields of the base type(s) before their own fields.

Thanks!

**Comment by Lessi30** [comment]
Hello everyone 

Unfortunately I have to inform you that I still have this problem despite the bugfix. The behaviour is more or less the same. When I set the new flag, my client shows the properties of the parent, but the method call still cannot be made. If I only set 
```csharp
OpcNodeSetImportOptions.CompleteDataTypeDefinitionFields
```
 then I get a BadInvalidArgument. If I set
```csharp
 OpcNodeSetImportOptions.CompleteDataTypeDefinitionFields & OpcNodeSetImportOptions.CompleteDataTypeDefinitionDefaultEncoding;
// or
 OpcNodeSetImportOptions.CompleteDataTypeDefinitionFields | OpcNodeSetImportOptions.CompleteDataTypeDefinitionDefaultEncoding;
```
then I get a conversion error that a byte[] cannot be converted into NewJobData. 

I have also tested things like doing the method definition with an OpcMethodDelegateCommand instead of Delegate, but no matter what I do, I don't get any success.

Can you please take [my example project](https://github.com/Lessi30/traeger-sdk-issue-15) into consideration again to verify if I am doing something wrong or the bug has not been fixed correctly by you? The project is divided into success and fail. The fail project should be solved, as the nodeset import is essential.

Greetings Alessio

**Comment by kpreisser** [comment]
Hi @Lessi30,
thanks for your feedback!

You're right, there seems to be another (independent) issue that causes the byte array of the `ExtensionObject` not to be decoded into the correct type before the method delegate is called. We are currently investigating this.

**Comment by kpreisser** [comment]
Hi @Lessi30,

it turns out that the defined type classes in your example project were not actually registered in the type system due to the project name being `"Traeger.ComplexParameter.Fail"`, and the SDK filters out assembly names that start with `"Traeger."` when searching for registerable types. If you rename your project so that it does not start with `"Traeger."`, calling the method should work.

(This is because some time ago we used separate assemblies for internal code whose name started with `Traeger.`, but these are no longer in use, so we probably should adjust this check to no longer exclude such assemblies.)

![Image](https://github.com/user-attachments/assets/a2e9ecaa-504c-4c6a-81fe-54d8add8ff8c)

![Image](https://github.com/user-attachments/assets/2015c17e-0bf6-4b26-a362-f2e1f1105e2b)

Thanks!

**Comment by larws** [comment]
Hi @kpreisser,
I have difficulties following your explanation since the projects in @Lessi30 sample repo only differ in the call to `OpcNodeSet.Load(@".\NodeSets\artemis 2.xml")` within the `Import` method of the NodeManager. Why is in one case the `CreateNodes` method relevant and in the case when `OpcNodeSet.Load` is called it is irrelevant? I would really appreciate your feedback.

**Comment by kpreisser** [comment]
Hi @larws,
thanks for your message!

AFAIK, when the call to `OpcNodeSet.Load(...)` is present in `OpcNodeManager.ImportNodes()`, and the node set already contains datatype nodes (`UADataType`), these nodes will be used for registration of the data types using their ID, and when `OpcNodeManager.CreateNodes()` returns `OpcDataTypeNode<T>` for the attributed classes (like `NewJobData`), they don't have an effect. In this case, when the dynamic type registration doesn't register the classes like `NewJobData` (and they are also not registered manually with `OpcData.RegisterType()`, the SDK can't match the data type ID to the class when reading a value.

On the other hand, when the `OpcNodeSet.Load(...)` call is not present, the data type is registered by returning `OpcDataTypeNode<T>` instances, and in that case they contain the type information in the generic type parameter `T`, so the SDK checks if it has already registered that type, and if not, registers it. This is why in that case the correct type instance (e.g. `NewJobData`) is used in the server when a client calls the method.

Thanks!

**Comment by Lessi30** [comment]
Hello everyone

Okay that is very unfortunate that a naming has led to this error. I think it should be fixed in any case, especially if this exclusion is no longer needed. Otherwise I would close this issue. 

Thank you for your help.
Greetings Lessi
